VERILOG_SOURCES += ../common/timescaleit.v
VERILOG_SOURCES += $(WORKSHOPROOT)/rtl/MemorySumming.v
VERILOG_SOURCES += $(WORKSHOPROOT)/rtl/Ram_1w_1r_2c.v

TOPLEVEL=MemorySumming
MODULE=blackboxAndClockTester
TIMESCALE = 1ns/1ps
WAVES = 1
VERILOG_INCLUDE_DIRS += ../common

include ../common/Makefile.sim