VERILOG_SOURCES += ../common/timescaleit.v $(WORKSHOPROOT)/rtl/Apb3Decoder.v
TOPLEVEL=Apb3Decoder
MODULE=Apb3DecoderTester
TIMESCALE = 1ns/1ps
WAVES = 1
VERILOG_INCLUDE_DIRS += ../common

include ../common/Makefile.sim