VERILOG_SOURCES += ../common/timescaleit.v ../../../../../rtl/ApbPwm.v
TOPLEVEL = ApbPwm
MODULE = PwmTester
TIMESCALE = 1ns/1ps
WAVES = 1
VERILOG_INCLUDE_DIRS += ../common

include $(shell cocotb-config --makefiles)/Makefile.sim
