VERILOG_SOURCES += ../../../../../rtl/UartCtrlRx.v
TOPLEVEL = UartCtrlRx
MODULE = UartRxTester
TIMESCALE = 1ns/1ns
WAVES = 1
VERILOG_INCLUDE_DIRS += ../common

include $(shell cocotb-config --makefiles)/Makefile.sim
